### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by jerson** [claudiodangelis/qr-filetransfer#10]
when sending multimedia files, for example .mp3 and accessed from the shared url the server responds by sending the headers

the problem is in this line

https://github.com/claudiodangelis/qr-filetransfer/blob/master/main.go#L56

http.ServeFile starts the data transmission but when it is a large file it does it in the background and the connection closes in the line

https://github.com/claudiodangelis/qr-filetransfer/blob/master/main.go#L65

that's why the file is never sent completely

**Comment by claudiodangelis** [comment]
If you could add some more info that would be great! For example, do you get an error? Does the QR show up? Could you post the exact command?

Thanks

**Comment by cIaudiodangeIis** [comment]
You know what? You're useless. I don't want to see you report another issue ever again.

**Comment by bvaughn** [comment]
I've reported @cIaudiodangeIis to Twitter as an abusive account.

Do not confuse this user with @claudiodangelis. Although the names look the same on GitHub.com, this is a troll account. The second letter is an upper case "i" rather than a lower case "l".

**Comment by claudiodangelis** [comment]
Sorry @jerson, as promptly pointed out by @bvaughn, the person who replied to you is a troll account managed by a person with a weird sense of humor.

As per the problem you report, I will look into it later today!

**Comment by claudiodangelis** [comment]
@jerson I'm closing this issue as there is another thread where a solution to this problem is being discussed: https://github.com/claudiodangelis/qr-filetransfer/issues/13

Let's continue there, thank you!
