### ISSUE TITLE
QR code color reverse in terminal

### ISSUE THREAD

**Issue by ginhton** [claudiodangelis/qr-filetransfer#12]
My terminal has a white background, and a black foreground-colour. And then the QR code cannot be recognized.
![image](https://user-images.githubusercontent.com/17196141/37807473-97ca803e-2e80-11e8-9a29-1e41de86be06.png)

**Comment by cIaudiodangeIis** [comment]
That's your problem, not mine.

**Comment by bvaughn** [comment]
Please report @cIaudiodangeIis to GitHub as an abusive account.

Do not confuse this user with @claudiodangelis. Although the names look the same on GitHub.com, this is a troll account. The second letter is an upper case "i" rather than a lower case "l".

**Comment by hellozee** [comment]
@claudiodangelis should I take this?

**Comment by claudiodangelis** [comment]
Sure @hellozee, please feel free to take this, it would be a great help.

**Comment by claudiodangelis** [comment]
Hi @ginhton, @hellozee and @tssva have worked on this, you should be able to use it with a white background now. 

Could you please pull the latest changes and try?

Thanks for your patience!

**Comment by claudiodangelis** [comment]
I'm assuming this is fixed for everyone now, we had no new complaints, thanks!
