### ISSUE TITLE
Support reading paths from stdin

### ISSUE THREAD

**Issue by sayanarijit** [claudiodangelis/qr-filetransfer#202]
I'm opening this issue because:

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

Hi again, is there any possibility of supporting reading file paths from stdin like [pipe-rename](https://github.com/marcusbuffett/pipe-rename)?

This will solve two main problems:

- I won't have to deal with [escaping file paths](https://github.com/sayanarijit/xplr/wiki/Hacks#sendreceive-files-via-qr-code-on-lan) that include white spaces. I can just use
   ```
   cat $XPLR_PIPE_RESULT_OUT | qrcp send -
   ```
- The input will not be limited to the maximum size of command-line arguments supported by the system.

**Comment by claudiodangelis** [comment]
Oh, very good suggestion indeed. I also want to add something like

```
# Say that you want to transfer the output of some command
some-command | qrcp
```

**Comment by claudiodangelis** [comment]
Hello, would something like this be an option?

```sh
qrcp send $(echo $XPLR_PIPE_RESULT_OUT)
```

**Comment by sayanarijit** [comment]
> Hello, would something like this be an option?
> 
> ```shell
> qrcp send $(echo $XPLR_PIPE_RESULT_OUT)
> ```
> 
> EDIT: this way it should already work with the current version.

Actually this is what I'm currently using. But when there are multiple inputs, this method has two issues I have listed.

- Having to properly quote/escape file paths with white spaces manually. Some tools allow null character `\0` as a separator. But it's much better to be able to pass newline separated paths via stdin.
- The number of commandline arguments that can be passed are limited and the limit is quite low on some systems. Normally other commandline tools can use something like xargs to workaround this limitation, but it won't work with qrcp (unless we're fine with repeating one shot download for every file).

**Comment by claudiodangelis** [comment]
Ok thanks, can you please paste here a sample content of `XPLR_PIPE_RESULT_OUT` containing multiple inputs?
I will use it as a test string to implement a solution.

Thanks!
C

**Comment by sayanarijit** [comment]
The value of `$XPLR_PIPE_RESULT_OUT` is the path to a text file that contains one or more newline delimited file paths that are selected (to be sent via qrcp).

So if you `cat $XPLR_PIPE_RESULT_OUT`, you get:

```
/path/to/file1
/path/to/file2
/path/to/file3
```

And so on.

So, I'm currently using something similar to `qrcp send $(cat $XPLR_PIPE_RESULT_OUT)`. ([See here](https://github.com/sayanarijit/qrcp.xplr/blob/d8cf4f9b57ae10b59c213eb46c5ff5aed793b3ac/init.lua#L28)). Which won't work if files with whitespaces are selected.

**Comment by claudiodangelis** [comment]
Ah ok, now I understand. What about a command line flag to read the list of files to be transferred from a file?
You would use it like:

```
qrcp send --from-file $XPLR_PIPE_RESULT_OUT
```

**Comment by sayanarijit** [comment]
Yes... that definitely works for this use case. IMO, reading from `stdin` (at-least by default) is more flexible, as it will make integrating qrcp with many CLI tools (other than xplr) easier.

For e.g. in Linux, with the `--from-file` option, one can do:

```
find . -name "*.go" | qrcp send --from-file /dev/stdin
```

By using `-` as a shortcut to `--from-file /dev/stdin` it'd look like:

```
find . -name "*.go" | qrcp send -
```

But the second approach allows us to abstract away the path to stdin, which will come in handy in Windows, as there's [apparently no equivalent to /dev/stdin](https://stackoverflow.com/a/7396793/5209439).

**Comment by sayanarijit** [comment]
It may also be possible to use `- <PATH>` as a direct shortcut to `--from-file <PATH>` and if `<PATH>` is not given, the lines will be read from the stdin.
