### ISSUE TITLE
Unable to install using instructions

### ISSUE THREAD

**Issue by fatso83** [claudiodangelis/qr-filetransfer#23]
By following the README I don't get an executable in my PATH. Tips?

```
$ apt install golang-go

$ go get -v github.com/claudiodangelis/qr-filetransfer

$ which qr-filetransfer

$  qr-filetransfer
qr-filetransfer: Could not find command

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu Bionic Beaver (development branch)"

$ go version
go version go1.10 linux/amd64
```

**Comment by claudiodangelis** [comment]
Hi @fatso83, it seems there is a typo, there it's `qr-` not `q2r-`, can you please confirm?

```
$ go get -v github.com/claudiodangelis/q2r-filetransfer
```


Thanks,
Claudio

**Comment by fatso83** [comment]
Edited (the command line was correct, just error when making issue). The files are checked out correctly too, in `~/go/github/...`

**Comment by claudiodangelis** [comment]
What does `echo $GOPATH` returns?

**Comment by fatso83** [comment]
This was just me not being familiar with the Go universe, and you set me on the right `PATH` (pun intended) :cat: 

I was expecting Go to automatically put these binaries on a global path, much like `npm install -g` would do, but it puts these files in `$GOBIN`, defaulting to `$GOPATH/bin` (where `GOPATH` defaults to `~/go`). Neither of these were set, but they do have defaults, so setting them didn't make life any different, but at least now I knew why.

It's because `$GOBIN` wasn't in my `PATH`, so basically adding:

```shell
export GOBIN=$HOME/go
export PATH=$PATH:$GOBIN
```

to my ~/.bashrc fixed the issue. You might want to make a note in the README to avoid noise like this :)

**Comment by claudiodangelis** [comment]
Glad to hear, yeah, might be a good idea to add that note for go's newcomers :-)
