### ISSUE TITLE
panic: bind: cannot assign requested address

### ISSUE THREAD

**Issue by rohand32** [claudiodangelis/qr-filetransfer#3]
I am getting following error after selecting the interface

![image](https://user-images.githubusercontent.com/12265908/37783531-bd7c58bc-2e1b-11e8-9b6f-2acf999508a6.png)

**Comment by r-chris** [comment]
Out of curiosity - has this been tested on a Mac ?

**Comment by rohand32** [comment]
I am testing it on Ubuntu 16.04

**Comment by claudiodangelis** [comment]
Thanks for reporting, @rohand32. It seems that the function that is supposed to return a random available port is not working, because it returns `0` (the zero-value of type `int`).

How did you install the tool? Thank you

**Comment by claudiodangelis** [comment]
Ok, glad to hear you found a workaround, I will look into this anyway, thanks!

I'm leaving this thread open for now just in case someone else bumps into the same problem.

Claudio

**Comment by rberenguel** [comment]
localhost being or not being mapped with 127.0.0.1 is kind of a regular issue between Mac and Linux from my experience too

**Comment by claudiodangelis** [comment]
@rohand32 can you please pull the new changes on the master branch and try again? I merged a change by @tssva which might be solve your issue.

Thanks

**Comment by claudiodangelis** [comment]
I'll close this one as we stopped receiving reports of the bug. 

Many thanks for reporting, @rohand32!
