### ISSUE TITLE
Support transfer a link

### ISSUE THREAD

**Issue by lunny** [claudiodangelis/qr-filetransfer#33]
I would like qr-filetransfer also support
```shell
qr-filetransfer https://www.google.com
```
That's easy but that I can transfer anything via the same tool.

**Comment by hellozee** [comment]
@claudiodangelis If no one hasn't taken this up, I would like to give this a shot.

**Comment by claudiodangelis** [comment]
Thanks for this feature request @lunny, indeed it might be helpful, although I'm not entirely sure it fits the tool's purpose, maybe @hellozee can take it up and experiment with it?

Thanks to both!

**Comment by hellozee** [comment]
@claudiodangelis made a PR regarding that, hoping the changes I made is enough and comply with the coding standard of the project.

**Comment by lunny** [comment]
@hellozee @claudiodangelis thanks

**Comment by claudiodangelis** [comment]
Hi @lunny, I thought that this is a bit out of scope, so I would prefer not to implement it into `qr-filetransfer`. 

Here's a faster option that does not even require pc and mobile to be on the same network. It requires the [qrencode](https://fukuchi.org/works/qrencode/) utility and [ImageMagick](https://www.imagemagick.org/script/download.php), which is probably already installed on your system:

```sh
display <(qrencode "https://google.com" -o -)
```

@hellozee, I really appreciated your effort, thank you very much for that, I hope you can contribute again (there are a lot of open issues!).

**Comment by hellozee** [comment]
@claudiodangelis no worries
