### ISSUE TITLE
Use ipv4 addresses instead of ipv6

### ISSUE THREAD

**Issue by jakebacker** [claudiodangelis/qr-filetransfer#39]
On Windows, the program uses ipv6 on most/all network interfaces. This seems to cause problems with both qr code readers as well as connecting to the computer

**Comment by claudiodangelis** [comment]
Which problems are you experiencing? IPv6 support was buggy until a couple hours ago, if you've run into these problems prior to that maybe you can try again...?

**Comment by jakebacker** [comment]
I just managed to make it work. It seems like the latest commit actually fixed it somehow.

**Comment by claudiodangelis** [comment]
Oh, great. I think we can close this thread now, thanks.
