### ISSUE TITLE
Scan QR code to insert a string to clipboard?

### ISSUE THREAD

**Issue by FrontMage** [claudiodangelis/qr-filetransfer#51]
Just a thought, wouldn't it be nice to just scan to the clipboard?

---

For example, scan to copy the result of a grep of a big log file.

**Comment by claudiodangelis** [comment]
As I suggested to another user who was proposing a similar feature, this could be easily achieved with a combination of the `qrencode` and `display` utilities:

```
display <(qrencode $(cat big.log | grep hi) -o -)
```

Please feel free to close this thread if this answers your question!

**Comment by FrontMage** [comment]
That is a good answer, closing it.
