### ISSUE TITLE
Server closes before download is completed

### ISSUE THREAD

**Issue by salgadobreno** [claudiodangelis/qr-filetransfer#52]
<img src="https://user-images.githubusercontent.com/397315/38094085-34011e74-3343-11e8-9fe1-111cc358f031.png" width="250">

I was trying to send some audios to my phone, on the first file, I got the behavior depicted in the image on the first try and on the second one the download finished successfully, when transferring the second audio I think I tried 3 times and got this behavior the 3 times, I don't know if this would be specific to my phone or something, but maybe an option to keep the server running or adding a delay to it could solve this(assuming I didn't do anything wrong).

Files were around 30mb of mp3. Using Ubuntu 16.04.

**Comment by claudiodangelis** [comment]
Hi, I think you are affected by this issue: https://github.com/claudiodangelis/qr-filetransfer/issues/13

Please check the last comment of that thread, the user has a working solution on their fork which needs testing, maybe you can have a look?

I will check It out myself in a few hours, thanks!

**Comment by salgadobreno** [comment]
Hey @claudiodangelis, sry for the delay, I've tried @tssva's branch and seems it's fixed there :+1: My only comment is that my previous install was running on go 1.6.3, I then tried building it on 1.7 and finally on 1.10 for it to build. Thank you both.
