### ISSUE TITLE
Append transfer progress indication to output

### ISSUE THREAD

**Issue by claudiodangelis** [claudiodangelis/qr-filetransfer#67]
If the `-quiet` flag isn't set, the tool should print the progress stages of the transfer, i.e.:

```sh
Transfering...
```

```sh
Done
```

```sh
Canceled
```

**Comment by mb-14** [comment]
I would like to work on this

**Comment by claudiodangelis** [comment]
Hi @mb-14, thanks for taking care of this! Looking forward to seeing your implementation. Any questions, let me know.
