### ISSUE TITLE
Sorry.It's my fault.

### ISSUE THREAD

**Issue by littlebear333** [claudiodangelis/qr-filetransfer#83]
I'm opening this issue because:

- [x] I have found a bug
- [ ] I want to request a feature
- [ ] I have a question
- [ ] Other

- My Go version is: _(paste the output of `go version` and remember that qr-filetransfer requires at least version 1.8 of Go)_
- My [GOPATH](https://github.com/golang/go/wiki/GOPATH) is set to: _(paste the output of `echo $GOPATH`)_

**Comment by claudiodangelis** [comment]
Hi @littlebear333, glad to hear the issue is solved now!
